export type Category =
  | "Fashion"
  | "Kids"
  | "Beauty"
  | "Home"
  | "Tech"
  | "Food"
  | "Services"
  | "Entertainment"
  | "Hobbies"
  | "Pets"
  | "Health"

export type Floor = 0 | 1 | 2 | 3 | 4

export interface Tenant {
  id: string
  name: string
  category: Category
  floor: Floor
  description: string
  rating?: number
  reviewCount?: number
  tags: string[]
  isAnchor: boolean
  phone?: string
  workingHours: string
  location?: string
}

export const categories: { value: Category | "all"; label: string; icon: string }[] = [
  { value: "all", label: "Все", icon: "Grid3X3" },
  { value: "Fashion", label: "Одежда", icon: "Shirt" },
  { value: "Kids", label: "Дети", icon: "Baby" },
  { value: "Beauty", label: "Красота", icon: "Sparkles" },
  { value: "Home", label: "Дом", icon: "Home" },
  { value: "Tech", label: "Техника", icon: "Smartphone" },
  { value: "Food", label: "Еда", icon: "UtensilsCrossed" },
  { value: "Services", label: "Услуги", icon: "Wrench" },
  { value: "Entertainment", label: "Развлечения", icon: "Gamepad2" },
  { value: "Hobbies", label: "Хобби", icon: "Palette" },
  { value: "Pets", label: "Питомцы", icon: "PawPrint" },
  { value: "Health", label: "Здоровье", icon: "Pill" },
]

export const tenants: Tenant[] = [
  // Цокольный этаж (Floor 0)
  {
    id: "vse-dlya-doma",
    name: "Всё для дома",
    category: "Home",
    floor: 0,
    description: "Гипермаркет товаров для дома, сада и огорода.",
    tags: ["дом", "сад", "огород", "товары для дома"],
    isAnchor: true,
    workingHours: "10:00 - 20:00",
    location: "Цокольный этаж",
  },
  {
    id: "statusdoor",
    name: "Statusdoor",
    category: "Home",
    floor: 0,
    description: "Салон дверей. Входные и межкомнатные двери.",
    tags: ["двери", "ремонт", "интерьер"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Цокольный этаж",
  },

  // Первый этаж (Floor 1)
  {
    id: "aptechnyy-sklad",
    name: "Аптечный склад",
    category: "Health",
    floor: 1,
    description: "Аптека, лекарственные средства.",
    tags: ["аптека", "лекарства", "здоровье"],
    isAnchor: true,
    workingHours: "10:00 - 20:00",
    location: "Павильон 2",
  },
  {
    id: "shevelyura",
    name: "Шевелюра",
    category: "Beauty",
    floor: 1,
    description: "Магазин профессиональной косметики для волос.",
    tags: ["волосы", "косметика", "уход"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Около эскалатора",
  },
  {
    id: "betkhoven",
    name: "Бетховен",
    category: "Pets",
    floor: 1,
    description: "Товары для домашних питомцев.",
    tags: ["животные", "питомцы", "корм"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 18",
  },
  {
    id: "mir-led",
    name: "Мир LED",
    category: "Tech",
    floor: 1,
    description: "Светодиодная продукция, люстры, лампы.",
    tags: ["освещение", "светодиоды", "лампы", "люстры"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 20",
  },
  {
    id: "kdv-candyland",
    name: "KDV Candyland",
    category: "Food",
    floor: 1,
    description: "Фирменный магазин кондитерских изделий.",
    tags: ["сладости", "конфеты", "печенье"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "1 этаж",
  },
  {
    id: "vita",
    name: "Vita",
    category: "Health",
    floor: 1,
    description: "Салон оптики, проверка зрения.",
    tags: ["оптика", "очки", "линзы", "зрение"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 17",
  },
  {
    id: "santehnika",
    name: "Сантехника",
    category: "Home",
    floor: 1,
    description: "Магазин сантехники.",
    tags: ["сантехника", "ремонт", "ванная"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 3",
  },
  {
    id: "kris-flowers",
    name: "Kris Flowers",
    category: "Services",
    floor: 1,
    description: "Цветочная мастерская, подарки.",
    tags: ["цветы", "букеты", "подарки"],
    isAnchor: false,
    workingHours: "до 23:00",
    location: "Павильон 5",
  },
  {
    id: "vape-studio",
    name: "Vape Studio Chita",
    category: "Services",
    floor: 1,
    description: "Магазин табака и курительных принадлежностей.",
    tags: ["вейп", "табак"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "1 этаж",
  },
  {
    id: "hao-he",
    name: "Хао Хэ",
    category: "Food",
    floor: 1,
    description: "Магазин продуктов и азиатских сладостей.",
    tags: ["азиатская кухня", "продукты", "сладости"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 16",
  },
  {
    id: "fragrance-secret",
    name: "Fragrance Secret",
    category: "Beauty",
    floor: 1,
    description: "Парфюмерия, масляные духи.",
    tags: ["парфюм", "духи", "масла"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Около лифта",
  },
  {
    id: "smart-case",
    name: "Smart Case",
    category: "Tech",
    floor: 1,
    description: "Аксессуары для телефонов.",
    tags: ["чехлы", "аксессуары", "телефоны"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "1 этаж",
  },
  {
    id: "fpro",
    name: "fpro",
    category: "Health",
    floor: 1,
    description: "Спортивное питание.",
    tags: ["спорт", "питание", "протеин"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 1",
  },
  {
    id: "beri-zaryad",
    name: "Бери Заряд",
    category: "Services",
    floor: 1,
    description: "Аренда зарядных устройств (Powerbank).",
    tags: ["зарядка", "пауэрбанк"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Автомат",
  },

  // Второй этаж (Floor 2)
  {
    id: "tutbatut",
    name: "ТутБатут",
    category: "Entertainment",
    floor: 2,
    description: "Батутно-развлекательный центр.",
    rating: 4.8,
    reviewCount: 150,
    tags: ["батуты", "дети", "развлечения", "спорт"],
    isAnchor: true,
    workingHours: "10:00 - 20:00",
    location: "Павильон 10",
  },
  {
    id: "prodalitr",
    name: "ПродаЛитЪ",
    category: "Hobbies",
    floor: 2,
    description: "Книжный магазин, канцтовары.",
    tags: ["книги", "канцелярия", "учёба"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "2 этаж",
  },
  {
    id: "stilnyy-dom",
    name: "Стильный дом",
    category: "Home",
    floor: 2,
    description: "Магазин мебели и декора.",
    tags: ["мебель", "декор", "интерьер"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "2 этаж",
  },
  {
    id: "legopolis",
    name: "Легополис",
    category: "Entertainment",
    floor: 2,
    description: "Игровая комната, LEGO.",
    tags: ["лего", "дети", "игры"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 6",
  },
  {
    id: "krasochnyy-mir",
    name: "Красочный мир",
    category: "Services",
    floor: 2,
    description: "Фотосалон, копицентр, печать фото.",
    tags: ["фото", "печать", "копии"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Отдел 18",
  },
  {
    id: "megafon-yota",
    name: "МегаФон / Yota",
    category: "Tech",
    floor: 2,
    description: "Салон сотовой связи.",
    tags: ["связь", "телефоны", "сим-карты"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 21",
  },
  {
    id: "klyovyy",
    name: "Клёвый",
    category: "Hobbies",
    floor: 2,
    description: "Товары для рыбалки и отдыха.",
    tags: ["рыбалка", "отдых", "туризм"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 21",
  },
  {
    id: "madam",
    name: "Мадам",
    category: "Fashion",
    floor: 2,
    description: "Магазин женской одежды, сумки.",
    tags: ["одежда", "женская одежда", "сумки"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 17",
  },
  {
    id: "novyy-detskiy",
    name: "Новый детский",
    category: "Kids",
    floor: 2,
    description: "Магазин детской одежды.",
    tags: ["дети", "одежда", "детская одежда"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 12",
  },
  {
    id: "mini-moda",
    name: "Mini Moda",
    category: "Kids",
    floor: 2,
    description: "Детская одежда и обувь.",
    tags: ["дети", "одежда", "обувь"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 7",
  },
  {
    id: "avon",
    name: "Avon",
    category: "Beauty",
    floor: 2,
    description: "Пункт выдачи / Косметика.",
    tags: ["косметика", "avon", "красота"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Бутик 34-35",
  },
  {
    id: "good-lak",
    name: "Good Лак",
    category: "Beauty",
    floor: 2,
    description: "Товары для ногтевого сервиса.",
    tags: ["маникюр", "ногти", "лак"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 8",
  },
  {
    id: "kotori",
    name: "Kotori",
    category: "Beauty",
    floor: 2,
    description: "Корейская косметика и продукция.",
    tags: ["корейская косметика", "уход", "красота"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 15",
  },
  {
    id: "ariya",
    name: "Ария",
    category: "Home",
    floor: 2,
    description: "Салон штор и домашнего текстиля.",
    tags: ["шторы", "текстиль", "интерьер"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 14",
  },
  {
    id: "logika",
    name: "Logika",
    category: "Entertainment",
    floor: 2,
    description: "Детская игровая комната.",
    tags: ["дети", "игры", "развлечения"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "2 этаж",
  },

  // Третий этаж (Floor 3)
  {
    id: "jam",
    name: "Джем (Jam)",
    category: "Food",
    floor: 3,
    description: "Кафе, столовая, пиццерия.",
    tags: ["еда", "кафе", "пицца", "обед"],
    isAnchor: true,
    workingHours: "10:00 - 20:00",
    location: "Павильон 22",
  },
  {
    id: "chudo-ruchki",
    name: "Чудо-ручки",
    category: "Hobbies",
    floor: 3,
    description: "Товары для творчества и рукоделия.",
    rating: 4.9,
    reviewCount: 200,
    tags: ["рукоделие", "творчество", "хобби"],
    isAnchor: true,
    workingHours: "10:00 - 20:00",
    location: "Отдел 4",
  },
  {
    id: "vallenssia",
    name: "Vallenssia",
    category: "Fashion",
    floor: 3,
    description: "Магазин обуви.",
    tags: ["обувь", "мода"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 19",
  },
  {
    id: "tochka-krasoty",
    name: "Точка Красоты",
    category: "Beauty",
    floor: 3,
    description: "Парикмахерская, салон красоты.",
    tags: ["парикмахерская", "красота", "стрижка"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Слева от лифта",
  },
  {
    id: "belyo-moyo",
    name: "Бельё Моё",
    category: "Fashion",
    floor: 3,
    description: "Магазин нижнего белья.",
    tags: ["бельё", "одежда"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 11",
  },
  {
    id: "di-lusso",
    name: "Di Lusso",
    category: "Fashion",
    floor: 3,
    description: "Салон мужской одежды.",
    tags: ["мужская одежда", "костюмы", "мода"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 8",
  },
  {
    id: "electra-style",
    name: "Electra Style",
    category: "Fashion",
    floor: 3,
    description: "Магазин женской одежды.",
    tags: ["женская одежда", "мода"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 6",
  },
  {
    id: "atomy",
    name: "Atomy",
    category: "Beauty",
    floor: 3,
    description: "Корейская косметика.",
    tags: ["корейская косметика", "уход"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 20",
  },
  {
    id: "sumkin-dom",
    name: "Сумкин Dom",
    category: "Fashion",
    floor: 3,
    description: "Магазин сумок и кожгалантереи.",
    tags: ["сумки", "кожгалантерея", "аксессуары"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 16",
  },
  {
    id: "nika",
    name: "Ника",
    category: "Services",
    floor: 3,
    description: "Ателье по пошиву и ремонту одежды.",
    tags: ["ателье", "пошив", "ремонт одежды"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 14",
  },
  {
    id: "art-deko",
    name: "Арт-деко",
    category: "Home",
    floor: 3,
    description: "Мебельный салон, корпусная мебель.",
    tags: ["мебель", "интерьер"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "3 этаж",
  },
  {
    id: "allo-ya-na-brovyakh",
    name: "Алло, я на бровях",
    category: "Beauty",
    floor: 3,
    description: "Студия красоты (брови, ресницы).",
    tags: ["брови", "ресницы", "красота"],
    isAnchor: false,
    workingHours: "10:00 - 20:00",
    location: "Павильон 17",
  },

  // Четвертый этаж (Floor 4)
  {
    id: "lider",
    name: "Лидер",
    category: "Fashion",
    floor: 4,
    description: "Магазин одежды и обуви (дискаунтер).",
    tags: ["одежда", "обувь", "дискаунтер", "скидки"],
    isAnchor: true,
    workingHours: "10:00 - 20:00",
    location: "Весь этаж",
  },
]
